name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Download Test Data
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Built-in token, no setup needed
        run: |
          # Download specific file from the specific tag
          gh release download timescales-data-v1 -p "data.zip"
          unzip data.zip
          
      - name: Install dependencies
        run: |
          sudo apt-get install -y gcovr libboost-all-dev
          
      - name: Configure & Build
        run: |
          cmake -B build -DENABLE_COVERAGE=ON
          cmake --build build

      - name: Test & Generate Report
        run: |
          # Run tests
          cd build/tests && ./unit_tests
          
          # Generate XML Report (Codecov needs XML)
          # We filter to include only 'include/' folder to match your setup
          gcovr -r ../.. --filter "../../include/" --xml -o coverage.xml
          
      # --- ADD THIS DEBUG STEP ---
      - name: Debug Coverage Artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-debug
          path: build/tests/coverage.xml
      
      - name: Upload to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./build/tests/coverage.xml
          fail_ci_if_error: true
